apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fast
  namespace: app-ts

spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: pv-fast